// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqPGetj3K9hh-afDNIrGsXSVARh3oiX0',
    appId: '1:650274209340:web:cfe13ae55e16e5b7db4d39',
    messagingSenderId: '650274209340',
    projectId: 'soar-2855a',
    authDomain: 'soar-2855a.firebaseapp.com',
    storageBucket: 'soar-2855a.appspot.com',
    measurementId: 'G-P4MQWWK072',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7ioeQvhffQ0rceK1qR9ZTqc4y7v5RCA',
    appId: '1:650274209340:android:e517e10d60d6a469db4d39',
    messagingSenderId: '650274209340',
    projectId: 'soar-2855a',
    storageBucket: 'soar-2855a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7CHPjMOvZaEXgFPOsnISeHZtv4fIC0N4',
    appId: '1:650274209340:ios:4376a7be541aee3adb4d39',
    messagingSenderId: '650274209340',
    projectId: 'soar-2855a',
    storageBucket: 'soar-2855a.appspot.com',
    iosClientId: '650274209340-2mcv7mvma00u47tqvjg2atnu5gcqg399.apps.googleusercontent.com',
    iosBundleId: 'com.example.soar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7CHPjMOvZaEXgFPOsnISeHZtv4fIC0N4',
    appId: '1:650274209340:ios:4376a7be541aee3adb4d39',
    messagingSenderId: '650274209340',
    projectId: 'soar-2855a',
    storageBucket: 'soar-2855a.appspot.com',
    iosClientId: '650274209340-2mcv7mvma00u47tqvjg2atnu5gcqg399.apps.googleusercontent.com',
    iosBundleId: 'com.example.soar',
  );
}
